myapp/urls.py
from django.urls import path, include
from rest_framework.routers import DefaultRouter
from rest_framework.authtoken.views import obtain_auth_token
from . import views

app_name = 'myapp'


router = DefaultRouter()
router.register('blogs', views.BlogViewSet)
router.register('index-sliders', views.IndexSliderViewSet)
router.register('about-us', views.AboutUsViewSet)
router.register('explore-top-subjects', views.ExploreTopSubjectsViewSet)
router.register('courses', views.CoursesViewSet)
router.register('teachers', views.TeachersViewSet)
router.register('testimonial-sliders', views.TestimonialSliderViewSet)
router.register('get-in-touch', views.GetInTouchViewSet)
router.register('categories', views.CategoryViewSet)

urlpatterns = [

    path('', views.index, name='index'),
    path('about/', views.about, name='about'),
    path('contact/', views.contact, name='contact'),
    path('course/', views.course, name='course'),
    path('single/<slug:slug>/', views.single, name='single'),
    path('blog/', views.blog, name='blog'),
    path('teacher/', views.teacher, name='teacher'),
    path('test/', views.testpage, name='test'),
    path('course-apply/', views.course_apply, name='course_apply'),
    path('course_blog/<slug:slug>/', views.course_blog, name='course_blog'),
    path('category/<slug:slug>/', views.category_posts, name='category_posts'),
    path('blog/<slug:slug>/', views.blog, name='blog_by_course'),

    path('auth/login/', views.login_page, name='login_page'),
    path('auth/logout/', views.logout_page, name='logout'),
    path('auth/register/', views.register_page, name='register_page'),
    path('auth/profile/', views.profile_page, name='profile'),

    path('api/', include(router.urls)),
    path('auth/', obtain_auth_token, name='api_token_auth'),
]

myproject/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls.i18n import i18n_patterns

urlpatterns = [
    path('i18n/', include('django.conf.urls.i18n')),
]
urlpatterns += i18n_patterns(
    path('admin/', admin.site.urls),
    path('', include('myapp.urls')),
)
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/base.html
{% load static %}
{% load i18n %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <title>{% block title %}{% endblock %}</title>
    <meta content="width=device-width, initial-scale=1.0" name="viewport">
    <meta content="Free HTML Templates" name="keywords">
    <meta content="Free HTML Templates" name="description">

    <!-- Favicon -->
    <link href="{% static 'img/favicon.ico' %}" rel="icon">

    <!-- Google Web Fonts -->
    <link rel="preconnect" href="https://fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css2?family=Poppins:wght@400;500;600;700&display=swap" rel="stylesheet">

    <!-- Font Awesome -->
    <link rel="stylesheet" href="{{ font_awesome_update.0.update_url }}">

    <!-- Libraries Stylesheet -->
    <link href="{% static 'lib/owlcarousel/assets/owl.carousel.min.css' %}" rel="stylesheet">

    <!-- Customized Bootstrap Stylesheet -->
    <link href="{% static 'css/style.css' %}" rel="stylesheet">


</head>

<body>
    <!-- Topbar Start -->
    <div class="container-fluid d-none d-lg-block">
        <div class="row align-items-center py-4 px-xl-5">
            <div class="col-lg-3">
                <a href="{% url 'myapp:index' %}" class="text-decoration-none">
                    <h1 class="m-0"><span class="text-primary">E</span>COURSES</h1>
                </a>
            </div>
            <div class="col-lg-3 text-right">
                <div class="d-inline-flex align-items-center">
                    <i class="fa fa-2x fa-map-marker-alt text-primary mr-3"></i>
                    <div class="text-left">
                        <h6 class="font-weight-semi-bold mb-1">Our Office</h6>
                        <small>{{get_in_touch.0.location}}</small>
                    </div>
                </div>
            </div>
            <div class="col-lg-3 text-right">
                <div class="d-inline-flex align-items-center">
                    <i class="fa fa-2x fa-envelope text-primary mr-3"></i>
                    <div class="text-left">
                        <h6 class="font-weight-semi-bold mb-1">Email Us</h6>
                        <small>{{get_in_touch.0.email}}</small>
                    </div>
                </div>
            </div>
            <div class="col-lg-3 text-right">
                <div class="d-inline-flex align-items-center">
                    <i class="fa fa-2x fa-phone text-primary mr-3"></i>
                    <div class="text-left">
                        <h6 class="font-weight-semi-bold mb-1">Call Us</h6>
                        <small>{{get_in_touch.0.phone_number}}</small>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- Topbar End -->

    <!-- Navbar Start -->
    <div class="container-fluid">
        <div class="row border-top px-xl-5">
            <!-- Subjects (Categories) Section -->
            <div class="col-lg-3 d-none d-lg-block">
                <a class="d-flex align-items-center justify-content-between bg-secondary w-100 text-decoration-none" data-toggle="collapse" href="#navbar-vertical" style="height: 67px; padding: 0 30px;">
                    <h5 class="text-primary m-0"><i class="fa fa-book-open mr-2"></i>Subjects</h5>
                    <i class="fa fa-angle-down text-primary"></i>
                </a>
                <nav class="collapse position-absolute navbar navbar-vertical navbar-light align-items-start p-0 border border-top-0 border-bottom-0 bg-light" id="navbar-vertical" style="width: calc(100% - 30px); z-index: 9;">
                    <div class="navbar-nav w-100">
                        {% if categories %}
                            {% for category in categories %}
                                <a href="{% url 'myapp:category_posts' category.slug %}" class="nav-item nav-link">
                                    {{ category.name }}
                                </a>
                            {% endfor %}
                        {% else %}
                            <span class="nav-item nav-link">No Subjects Found</span>
                        {% endif %}
                    </div>
                </nav>
            </div>

            <!-- Main Navigation -->
            <div class="col-lg-9">
                <nav class="navbar navbar-expand-lg bg-light navbar-light py-3 py-lg-0 px-0">
                    <a href="" class="text-decoration-none d-block d-lg-none">
                        <h1 class="m-0"><span class="text-primary">E</span>COURSES</h1>
                    </a>
                    <button type="button" class="navbar-toggler" data-toggle="collapse" data-target="#navbarCollapse">
                        <span class="navbar-toggler-icon"></span>
                    </button>
                    <div class="collapse navbar-collapse justify-content-between" id="navbarCollapse">
                        <div class="navbar-nav py-0">
                            <a href="{% url 'myapp:index' %}" class="nav-item nav-link {% if request.path == '/' %}active{% endif %}">{% trans "Home" %}</a>
                            <a href="{% url 'myapp:about' %}" class="nav-item nav-link {% if request.path == '/about/' %}active{% endif %}">About</a>
                            <a href="{% url 'myapp:course' %}" class="nav-item nav-link {% if request.path == '/course/' %}active{% endif %}">Courses</a>
                            <a href="{% url 'myapp:teacher' %}" class="nav-item nav-link {% if request.path == '/teacher/' %}active{% endif %}">Teachers</a>
                            <a href="{% url 'myapp:blog' %}" class="nav-item nav-link {% if request.path == '/blog/' %}active{% endif %}">Blog</a>
                            <a href="{% url 'myapp:contact' %}" class="nav-item nav-link {% if request.path == '/contact/' %}active{% endif %}">Contact</a>
                        </div>
                        {% if user.is_authenticated %}
                        <div>
                            <a class="btn btn-primary py-2 px-4 ml-auto d-none d-lg-block" href="{% url 'myapp:profile' %}">{{ user.username }}</a>
                        </div>
                        <div>
                            <a class="btn btn-primary py-2 px-4 ml-auto d-none d-lg-block" href="{% url 'myapp:logout' %}">Logout</a>
                        </div>
                        {% else %}
                        <a class="btn btn-primary py-2 px-4 ml-auto d-none d-lg-block" href="{% url 'myapp:login_page' %}">Join Now</a>
                        {% endif %}
                    </div>
                </nav>
            </div>
        </div>
    </div>
    <!-- Navbar End -->

    {% block content %}{% endblock %}

    <!-- Footer Start -->
    <div class="container-fluid bg-dark text-white py-5" style="margin-top: 90px;">
      <div class="container">
        <div class="row g-4">
          <div class="col-md-4">
            <h5 class="text-primary text-uppercase mb-4" style="letter-spacing: 5px;">Get In Touch</h5>
            <p><i class="fa fa-map-marker-alt mr-2"></i>{{ get_in_touch.0.location }}</p>
            <p><i class="fa fa-phone-alt mr-2"></i>{{ get_in_touch.0.phone_number }}</p>
            <p><i class="fa fa-envelope mr-2"></i>{{ get_in_touch.0.email }}</p>
            <div class="d-flex justify-content-start mt-4">
              <a class="btn btn-outline-light btn-square mr-2" href="{{ get_in_touch.0.social_media_url_1 }}" target="_blank">
                  <i class="fab fa-{{ get_in_touch.0.social_media_icon_1 }}"></i>
              </a>
              <a class="btn btn-outline-light btn-square mr-2" href="{{ get_in_touch.0.social_media_url_2 }}" target="_blank">
                  <i class="fab fa-{{ get_in_touch.0.social_media_icon_2 }}"></i>
              </a>
              <a class="btn btn-outline-light btn-square mr-2" href="{{ get_in_touch.0.social_media_url_3 }}" target="_blank">
                  <i class="fab fa-{{ get_in_touch.0.social_media_icon_3 }}"></i>
              </a>
              <a class="btn btn-outline-light btn-square" href="{{ get_in_touch.0.social_media_url_4 }}" target="_blank">
                  <i class="fab fa-{{ get_in_touch.0.social_media_icon_4 }}"></i>
              </a>
            </div>
          </div>
          <div class="col-md-4">
            <h5 class="text-primary text-uppercase mb-4" style="letter-spacing: 5px;">Our Courses</h5>
            <div class="d-flex flex-column">
              {% for course in courses %}
              <a class="text-white mb-2" href="{% url 'myapp:course_blog' course.slug %}"><i class="fa fa-angle-right mr-2"></i>{{ course.title }}</a>
              {% endfor %}
            </div>
          </div>
          <div class="col-md-4">
            <h5 class="text-primary text-uppercase mb-4" style="letter-spacing: 5px;">Quick Links</h5>
            <div class="d-flex flex-column">
              <a class="text-white mb-2" href="{% url 'myapp:about' %}"><i class="fa fa-angle-right mr-2"></i>About Us</a>
              <a class="text-white mb-2" href="{% url 'myapp:teacher' %}"><i class="fa fa-angle-right mr-2"></i>Teacher</a>
              <a class="text-white mb-2" href="{% url 'myapp:contact' %}"><i class="fa fa-angle-right mr-2"></i>Contact</a>
              <a class="text-white mb-2" href="{% url 'myapp:blog' %}"><i class="fa fa-angle-right mr-2"></i>Blog</a>
            </div>
          </div>
        </div>
      </div>
    </div>
    <!-- Footer End -->

    <a href="#" class="btn btn-lg btn-primary btn-lg-square back-to-top"><i class="fa fa-angle-double-up"></i></a>
    <!-- JavaScript Libraries -->
    <script src="https://code.jquery.com/jquery-3.4.1.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.bundle.min.js"></script>
    <script src="{% static 'lib/easing/easing.min.js' %}"></script>
    <script src="{% static 'lib/owlcarousel/owl.carousel.min.js' %}"></script>

    <!-- Contact Javascript File -->
    <script src="{% static 'mail/jqBootstrapValidation.min.js' %}"></script>
    <script src="{% static 'mail/contact.js' %}"></script>

    <!-- Template Javascript -->
    <script src="{% static 'js/main.js' %}"></script>
</body>

</html>

templates/blog.html
{% extends 'base.html' %}
{% load static %}

{% block title %}
    {% if selected_category %}
        {{ selected_category.name }}
    {% else %}
        Blog
    {% endif %}
{% endblock %}

{% block content %}
    <!-- Header Start -->
    <div class="container-fluid page-header" style="margin-bottom: 90px;">
        <div class="container">
            <div class="d-flex flex-column justify-content-center" style="min-height: 300px">
                {% if selected_category %}
                    <h3 class="display-4 text-white text-uppercase">{{ selected_category.name }}</h3>
                {% else %}
                    <h3 class="display-4 text-white text-uppercase">Blog</h3>
                {% endif %}
                <div class="d-inline-flex text-white">
                    <p class="m-0 text-uppercase">
                        <a class="text-white" href="{% url 'myapp:index' %}">Home</a>
                    </p>
                    <i class="fa fa-angle-double-right pt-1 px-3"></i>
                    {% if selected_category %}
                        <p class="m-0 text-uppercase">{{ selected_category.name }}</p>
                    {% else %}
                        <p class="m-0 text-uppercase">Blog</p>
                    {% endif %}
                </div>
            </div>
        </div>
    </div>
    <!-- Header End -->

    <!-- Blog Start -->
    <div class="container-fluid py-5">
        <div class="container py-5">
            <div class="row">
                <!-- Blog Posts Section -->
                <div class="col-lg-8">
                    {% if page_object and page_object.object_list %}
                        <div class="row pb-3">
                            {% for blog in page_object %}
                                <div class="col-lg-6 mb-4">
                                    <div class="blog-item position-relative overflow-hidden rounded mb-2">
                                        <img class="img-fluid" src="{{ blog.image.url }}" alt="{{ blog.title }}">
                                        <a class="blog-overlay text-decoration-none" href="{% url 'myapp:single' slug=blog.slug %}">
                                            <h5 class="text-white mb-3">{{ blog.title }}</h5>
                                            <p class="text-primary m-0">{{ blog.created_at|date:"d M Y" }}</p>
                                        </a>
                                    </div>
                                </div>
                            {% endfor %}
                        </div>
                        <div class="col-12">
                            <nav aria-label="Page navigation">
                                <ul class="pagination pagination-lg justify-content-center mb-0">
                                    {% for num in page_object.paginator.page_range %}
                                        <li class="page-item {% if num == page_object.number %}active{% endif %}">
                                            <a class="page-link" href="?page={{ num }}">{{ num }}</a>
                                        </li>
                                    {% endfor %}
                                </ul>
                            </nav>
                        </div>
                    {% else %}
                        <p>Heç bir blog postu tapılmadı.</p>
                    {% endif %}
                </div>

                <!-- Sidebar -->
                <div class="col-lg-4 mt-5 mt-lg-0">
                    <!-- Search Form -->
                    <div class="mb-5">
                        {% if course %}
                            <form action="{% url 'myapp:blog_by_course' course.slug %}" method="get">
                        {% else %}
                            <form action="{% url 'myapp:blog' %}" method="get">
                        {% endif %}
                                <div class="input-group">
                                    <input name="keyword" type="text" class="form-control form-control-lg" placeholder="Keyword" aria-label="Search">
                                    <div class="input-group-append">
                                        <button class="btn btn-primary" type="submit">
                                            <i class="fa fa-search"></i>
                                        </button>
                                    </div>
                                </div>
                            </form>
                    </div>

                    <!-- Categories -->
                    <div class="mb-5">
                        <h3 class="text-uppercase mb-4" style="letter-spacing: 5px;">Categories</h3>
                        <ul class="list-group list-group-flush">
                            {% for category in categories %}
                                <li class="list-group-item d-flex justify-content-between align-items-center px-0">
                                    <a href="{% url 'myapp:category_posts' category.slug %}" class="text-decoration-none h6 m-0">
                                        {{ category.name }}
                                    </a>
                                </li>
                            {% endfor %}
                        </ul>
                    </div>

                    <!-- Recent Posts -->
                    <div class="mb-5">
                        <h3 class="text-uppercase mb-4" style="letter-spacing: 5px;">Recent Posts</h3>
                        {% for post in last_posts %}
                            <a class="d-flex align-items-center text-decoration-none mb-3" href="{% url 'myapp:single' slug=post.slug %}">
                                <img class="img-fluid rounded" src="{{ post.image.url }}" alt="{{ post.title }}">
                                <div class="pl-3">
                                    <h6 class="m-1">{{ post.title }}</h6>
                                    <small>{{ post.created_at|date:"d M Y" }}</small>
                                </div>
                            </a>
                        {% endfor %}
                    </div>
                    <!-- Subscription Form -->
                    <div class="mb-5">
                        {% if messages %}
                            <div class="mb-4">
                                {% for message in messages %}
                                    {% if message.tags == "error" %}
                                        <div class="alert alert-danger">
                                            {{ message }}
                                        </div>
                                    {% elif message.tags == "success" %}
                                        <div class="alert alert-success">
                                            {{ message }}
                                        </div>
                                    {% else %}
                                        <div class="alert alert-info">
                                            {{ message }}
                                        </div>
                                    {% endif %}
                                {% endfor %}
                            </div>
                        {% endif %}
                        <form method="post" action="{% url 'myapp:blog' %}">
                            {% csrf_token %}
                            <div class="input-group">
                                <input type="email" name="email" class="form-control form-control-lg" placeholder="E-mail" required>
                                <div class="input-group-append">
                                    <button class="btn btn-primary" type="submit">Subscription</button>
                                </div>
                            </div>
                        </form>
                    </div>
                </div>
                <!-- End Sidebar -->
            </div>
        </div>
    </div>
    <!-- Blog End -->
{% endblock %}

templates/login_page.html
{% extends 'base.html' %}

{% load static %}

{% block title %}Register {% endblock %}

{% block content %}
    <!-- Header Start -->
    <div class="container-fluid page-header" style="margin-bottom: 90px;">
        <div class="container">
            <div class="d-flex flex-column justify-content-center" style="min-height: 300px">
                <h3 class="display-4 text-white text-uppercase">Login</h3>
                <div class="d-inline-flex text-white">
                </div>
            </div>
        </div>
    </div>
    <!-- Header End -->

    <div class="container-fluid bg-registration py-5" style="margin: 90px 0;">
    <div class="container py-5">
        <div class="row align-items-center">
            <div class="col-lg-7 mb-5 mb-lg-0">
                <div class="mb-4">
                    <h5 class="text-primary text-uppercase mb-3" style="letter-spacing: 5px;">Need Any Courses</h5>
                    <h1 class="text-white">30% Off For New Students</h1>
                </div>
                <p class="text-white">Unlock your learning potential with an exclusive discount for new students. Enroll today and start your journey!</p>
                <ul class="list-inline text-white m-0">
                    <li class="py-2"><i class="fa fa-check text-primary mr-3"></i>Learn at your own pace with expert instructors.</li>
                    <li class="py-2"><i class="fa fa-check text-primary mr-3"></i>Access high-quality study materials anytime.</li>
                    <li class="py-2"><i class="fa fa-check text-primary mr-3"></i>Boost your skills and career opportunities.</li>
                </ul>
            </div>
            <div class="col-lg-5">
                <div class="card border-0">
                    <div class="card-header bg-light text-center p-4">
                        <h1 class="m-0">Login</h1>
                    </div>
                    <div class="card-body rounded-bottom bg-primary p-5">
                        <form method="POST" action="{% url 'myapp:login_page' %}">
                            {% csrf_token %}
                            <div class="form-group">
                                <input type="text" class="form-control border-0 p-4" placeholder="Username" required="required" name="username" />
                            </div>
                            <div class="form-group">
                                <input type="password" class="form-control border-0 p-4" placeholder="Password" required="required" name="password" />
                            </div>
                            <div>
                                <button class="btn btn-dark btn-block border-0 py-3" type="submit">Login</button>
                            </div>
                        </form>
                        {% if messages %}
                          {% for message in messages %}
                            {% if message.tags == 'success' %}
                              <div class="alert alert-success" role="alert">
                                {{ message }}
                              </div>
                            {% elif message.tags == 'error' %}
                              <div class="alert alert-danger" role="alert">
                                {{ message }}
                              </div>
                            {% else %}
                              <div class="alert alert-info" role="alert">
                                {{ message }}
                              </div>
                            {% endif %}
                          {% endfor %}
                        {% endif %}
                        <div class="text-center mt-3">
                            <a href="{% url 'myapp:register_page' %}" class="btn btn-light btn-block border-0 py-3">
                                Create an Account
                            </a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

templates/single.html
{% extends 'base.html' %}
{% load static %}

{% block title %}Single{% endblock %}

{% block content %}
    <!-- Header Start -->
    <div class="container-fluid page-header" style="margin-bottom: 90px;">
        <div class="container">
            <div class="d-flex flex-column justify-content-center" style="min-height: 300px">
                <h3 class="display-4 text-white text-uppercase">Single</h3>
                <div class="d-inline-flex text-white">
                    <p class="m-0 text-uppercase"><a class="text-white" href="{% url 'myapp:index' %}">Home</a></p>
                    <i class="fa fa-angle-double-right pt-1 px-3"></i>
                    <p class="m-0 text-uppercase">Single</p>
                </div>
            </div>
        </div>
    </div>
    <!-- Header End -->

    <!-- Detail Start -->
    <div class="container-fluid py-5">
        <div class="container py-5">
            <div class="row">
                <div class="col-lg-8">
                    <div class="mb-5">
                        <h6 class="text-primary mb-3">{{ post.created_at|date:"M d, Y" }}</h6>
                        <h1 class="mb-5">{{ post.title|linebreaksbr }}</h1>
                        <img class="img-fluid rounded w-100 mb-4" src="{{ post.image.url }}" alt="Image">
                        <p>{{ post.description|linebreaksbr }}</p>
                        {% if post.title2 %}
                            <h2 class="mb-4">{{ post.title2|linebreaksbr }}</h2>
                        {% endif %}
                        {% if post.image2 %}
                            <img class="img-fluid rounded w-50 float-left mr-4 mb-3" src="{{ post.image2.url }}" alt="Image">
                        {% endif %}
                        <p>{{ post.main_content|linebreaksbr }}</p>
                    </div>

                    <div class="mb-5">
                        <h3 class="text-uppercase mb-4" style="letter-spacing: 5px;">{{ comments|length }} Rəy</h3>
                        {% for comment in comments %}
                        <div class="media mb-4">
                            {% if comment.author and comment.author.profile_picture %}
                                <img src="{{ comment.author.profile_picture.url }}" alt="Profile Picture"
                                     class="img-fluid rounded-circle mr-3 mt-1" style="width: 45px;">
                            {% else %}
                                <img src="{% static 'img/user.jpg' %}" alt="Default User"
                                     class="img-fluid rounded-circle mr-3 mt-1" style="width: 45px;">
                            {% endif %}
                            <div class="media-body">
                                <h6>
                                    {% if comment.author %}
                                        {{ comment.author.user.username }}
                                    {% else %}
                                        Anonim
                                    {% endif %}
                                    <small>
                                        <i>{{ comment.published_date|date:"d M Y H:i a" }}</i>
                                    </small>
                                </h6>
                                <p>{{ comment.body|linebreaksbr }}</p>
                            </div>
                        </div>
                        {% empty %}
                        <p>Hələ heç bir rəy yoxdur.</p>
                        {% endfor %}
                    </div>
                    {% if user.is_authenticated %}
                    <div class="bg-light rounded p-5">
                        <h3 class="text-uppercase mb-4" style="letter-spacing: 5px;">Rəy Yazın</h3>
                        {% if new_comment %}
                        <div class="alert alert-success">
                            Rəyiniz uğurla əlavə edildi!
                        </div>
                        {% endif %}
                        <form method="post">
                            {% csrf_token %}
                            {{ comment_form.as_p }}
                            <button type="submit" class="btn btn-primary py-md-2 px-md-4 font-weight-semi-bold">Rəyi Göndər</button>
                        </form>
                    </div>
                    {% else %}
                    <a class="btn btn-primary py-2 px-4 ml-auto d-none d-lg-block" href="{% url 'myapp:login_page' %}">Rəy yazmaq üçün daxil olun</a>
                    {% endif %}
                </div>

                <div class="col-lg-4 mt-5 mt-lg-0">
                    <div class="d-flex flex-column text-center bg-dark rounded mb-5 py-5 px-4">
                        <img src="{{ post.author.profile_picture.url }}" class="img-fluid rounded-circle mx-auto mb-3" style="width: 100px;">
                        <h3 class="text-primary mb-3">{{ post.author.user.username }}</h3>
                        <h3 class="text-uppercase mb-4" style="letter-spacing: 5px;">Tag Cloud</h3>
                        <p class="text-white m-0">{{ post.author.bio }}</p>
                    </div>
                    <div class="mb-5">
                        <h3 class="text-uppercase mb-4" style="letter-spacing: 5px;">Kateqoriyalar</h3>
                        <ul class="list-group list-group-flush">
                            {% for category in categories %}
                            <li class="list-group-item d-flex justify-content-between align-items-center px-0">
                                <a href="{% url 'myapp:category_posts' category.slug %}" class="text-decoration-none h6 m-0">
                                    {{ category.name }}
                                </a>
                            </li>
                            {% endfor %}
                        </ul>
                    </div>
                    <div class="mb-5">
                        <h3 class="text-uppercase mb-4" style="letter-spacing: 5px;">Son Yazılar</h3>
                        {% for p in last_posts %}
                        <a class="d-flex align-items-center text-decoration-none mb-3" href="{% url 'myapp:single' slug=p.slug %}">
                            <img class="img-fluid rounded" src="{{ p.image.url }}" alt="{{ p.title }}">
                            <div class="pl-3">
                                <h6 class="m-1">{{ p.title }}</h6>
                                <small>{{ p.created_at|date:"d M Y" }}</small>
                            </div>
                        </a>
                        {% endfor %}
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- Detail End -->
{% endblock %}

templates/testpage.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Testpage</title>
</head>
<body>
{% if user.is_authenticated %}
    <h1>Welcome, {{ user.username }}!</h1>
    <a href="{% url 'logout' %}">Logout</a>
{% else %}
    <h1>Login</h1>
{% endif %}
<p>
  Bu cümlədə<br>mütləq sətir fasiləsi var.
</p>

<p>
  UzunURL: https://verylongurl.example.com/path/to/resource.jpg
  <!-- sətir dolduqda brauzer burada qırılacaq -->
</p>

</body>
</html>